name: Lint

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24.x
      - name: Set up PNPM
        run: corepack enable
      - name: Prepare Socket Firewall
        uses: SocketDev/action@2d3f25590c6ed6ba11a9a14c064d962a3a04698f # v1.3.1
        with:
          mode: firewall-free
      - name: Install deps (Socket Firewall ✔️)
        run: sfw pnpm ci

      - run: pnpm run lint
