name: All Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: "pnpm"
      - name: Set up PNPM
        run: corepack enable
      - run: pnpm install

      - run: pnpm run lint
      - run: pnpm run typecheck
      - run: pnpm run test:unit
      - run: pnpm run build
